---
title: "Registration Report"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    orientation: row
    theme: bootstrap
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(tidyverse)
library(osfr)
library(highcharter)
library(DT)
library(here)
library(googlesheets4)

##data imports

form_data <- read_csv(here::here('Monthly_Reports/Registrations/form_type_monthly.csv')) 
total_regs <- read_csv(here::here('Monthly_Reports/Registrations/monthly_total_regs.csv')) %>%
                    mutate(keen.timestamp = as.Date(keen.timestamp))
reg_targets <- read_sheet('https://docs.google.com/spreadsheets/d/1b7Rgo_tdUvNmmjO_EUIn_e3ZJfecVDiycBN_d9HoEB4/') %>%
                  select(date, registered_projects.targets) %>%
                  mutate(date = as.Date(date))

# merge projects and actuals
total_regs <- total_regs %>%
                left_join(reg_targets, by = c('keen.timestamp' = 'date'))
```

Row {data-height=175}
-------------------------------------


### New Top-level Registrations {.value-box}

```{r}
valueBox(value = total_regs %>% arrange(desc(keen.timestamp)) %>% slice(1L) %>% select(monthly_diff_total),
    icon = "fa-pencil")
```

### New Top-Level Embargoed Registrations  {.value-box}

```{r}
valueBox(value = total_regs %>% arrange(desc(keen.timestamp)) %>% slice(1L) %>% select(monthly_diff_embargo),
    icon = "fa-user-secret")
```

### New Top-Level Registration Withdrawals {.value-box}

```{r}
valueBox(value = total_regs %>% arrange(desc(keen.timestamp)) %>% slice(1L) %>% select(monthly_diff_withdraws),
    icon = "fa-trash")
```

Row {.tabset data-height=650}
-----------------------------------------------------------------------

### Total Registrations
```{r}
total_regs %>% 
  select(keen.timestamp, registered_projects.monthly_diff, registered_projects.targets) %>% 
  pivot_longer(cols = starts_with('registered'), names_to = 'type', names_prefix = 'registered_projects.', values_to = 'count') %>%
  hchart(., type = 'line',
         hcaes(x = keen.timestamp,
               y = count,
               group = type)) %>%
  hc_exporting(
    enabled = TRUE, filename="reg_form_counts", 
              formAttributes=list(target="_blank"),
               buttons=list(contextButton=list(
               text="Export", theme=list(fill="transparent"))))
```

### Registrations by Form Type

```{r}

top_forms <- form_data %>%
                group_by(name) %>%
                summarize(total_regs = sum(reg_events)) %>%
                arrange(desc(total_regs)) %>%
                pull(name)

n <- 5

fewer_forms_data <- form_data %>%
                        group_by(name) %>%
                        mutate(form = case_when(name %in% top_forms[1:n] ~ name, 
                                                    TRUE ~ "Other")) %>%
                        ungroup()

fewer_forms_data %>%
  group_by(date, form) %>%
  summarise(reg_events = sum(reg_events), retract_events = sum(retract_events), net_events = sum(net_events)) %>%
  hchart(., type = 'line',
         hcaes(x = date,
               y = net_events,
               group = form)) %>%
  hc_exporting(
    enabled = TRUE, filename="reg_form_counts", 
              formAttributes=list(target="_blank"),
               buttons=list(contextButton=list(
               text="Export", theme=list(fill="transparent"))))
```

Row
-----------------------------------------------------------------------
```{r}
fewer_forms_data %>%
  select(date, name, form, reg_events, retract_events, net_events) %>%
  datatable(extensions = 'Buttons',  
            options = list(dom = 'Bfrtip', buttons = list( list(extend = 'collection', buttons = list(list(extend='csv',filename='reg_form_counts.csv'),
                                                                 list(extend='excel', filename = 'reg_form_counts.xlsx') ),text="Download"))))
```
