---
title: "preprint_impact_testing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#loading libraries
library(httr)
library(tidyverse)
library(here)
library(jsonlite)
library(lubridate)
library(reticulate)

url <- 'https://api.staging.osf.io/_/metrics/preprints/'
osf_auth <- Sys.getenv("osf_preprintimpact_testing_auth")
auth_header <- httr::add_headers('Authorization' = paste('Bearer', osf_auth))

use_condaenv(condaenv = "myenv", conda = "/Users/courtneysoderberg/opt/anaconda3/bin/python")
```

## R Markdown

```{r impact api function}

##function to return cleaned tibble of impact API call return
impact_tibble <- function(call_output) {
  prettify_json <- prettify(call_output)
  json_to_r <- fromJSON(prettify_json)
  
  call_data <- as.data.frame(unlist(json_to_r)) %>% 
    rownames_to_column() %>% 
    filter(!is.na(unlist(json_to_r))) %>% 
    rename(downloads = `unlist(json_to_r)`) %>% 
    slice(-1)
  
  call_data <- separate(data = call_data, col = rowname, into = paste("V", 1:4, sep = '_'), sep = "\\.") %>% 
    select(V_2,V_4,downloads) %>% 
    rename(date = V_2, preprint_guid = V_4) %>% 
    mutate(preprint_guid = str_sub(preprint_guid, 1, 5))
  
  call_data <- as_tibble(call_data) %>% 
    mutate(downloads = as.numeric(as.character(downloads))) %>% 
    mutate(date = ymd_hms(date))
  
  return(call_data)
}
```

## Test calls to api

Preprint guids on staging that can be used for testing (i.e. have at least 1 view and perhaps some downloads): c8ufs, ytnbv, dbyt3, cbxwt, auets, rmy2g, dzs5w, bq3gr, 8knvf, pnae3, remqt, c4k67

```{r api testing, echo=FALSE}
call_1_downloads <- GET(url = paste0(url, 'downloads/?guids=c8ufs,ytnbv&start_datetime=2020-01-13&end_datetime=2020-01-14&interval=second'), auth_header)
impact_tibble(call_1_downloads)

call_1_views <- GET(url = paste0(url, 'views/?guids=c8ufs,ytnbv&start_datetime=2020-01-01&end_datetime=2020-03-12&interval=day'), auth_header)
impact_tibble(call_1_views)
```

## Test advanced queries to elastic search directly

```{python setup}
import requests

METRICS_BASE = r.url
TOKEN = r.osf_auth

headers = {
    'Content-Type': 'application/vnd.api+json',
    'Authorization': 'Bearer {}'.format(TOKEN)
}

post_url = '{}downloads/'.format(METRICS_BASE)

## how many times did logged in users download preprints, and which preprints did they download
query = {
            "aggs": {
                "preprints_per_month_per_user" : {
                    "composite": {
                        "size" : 20,
                        "sources" : [
                            {"date":{"date_histogram":{"field":"timestamp","interval":"second","format": "yyyy-MM-dd HH:mm"}}},
                            {"user_id":{"terms":{"field":"user_id"}}},
                            {"preprint_id":{"terms":{"field":"preprint_id"}}}
                        ]
                    }
                }
            }
        }


payload = {
    'data': {
        'type': 'preprint_metrics',
        'attributes': {
            'query': query
        }
    }
}





res = requests.post(post_url, headers=headers, json=payload)
output = res.json()['aggregations']['preprints_per_month_per_user']['buckets']
```

```{python}

# downloads from logged_in users
query = {
    "query": {
         "exists" : { "field" : "user_id" }
    },
     "aggs" : {
        "preprints_from_2019": {
            "filter": {
                "range" : {
                    "timestamp" : {
                        "gte" : "2018-01-01",
                        "lt" : "2019-12-31"
                    }
                }
            },
            "aggs": {
                "users" : {
                    "terms" : {
                        "field" : "user_id",
                        "size" : 250
                    }
                }
            }
        }
    }
}


payload = {
    'data': {
        'type': 'preprint_metrics',
        'attributes': {
            'query': query
        }
    }
}

res = requests.post(post_url, headers=headers, json=payload)
login_users = res.json()['aggregations']['preprints_from_2019']['users']['buckets']
```

```{python}
# downloads by service by month in 2019
query = {
     "aggs" : {
        "preprints_from_2019": {
            "filter": {
                "range" : {
                    "timestamp" : {
                        "gte" : "2019-01-01",
                        "lt" : "2020-03-13"
                    }
                }
            },
            "aggs": {
                "service" : {
                    "terms" : { 
                      "field" : "provider_id",
                      "size" : 20
                      },
                      "aggs": {
                        "downloads_per_month" : {
                          "date_histogram" :{
                            "field":"timestamp",
                            "interval":"month",
                            "format": "yyyy-MM-dd HH:mm"
                          }
                        }
                      }
                }
            }
        }
    }
}


payload = {
    'data': {
        'type': 'preprint_metrics',
        'attributes': {
            'query': query
        }
    }
}

res = requests.post(post_url, headers=headers, json=payload)
services_by_month = res.json()['aggregations']['preprints_from_2019']['service']['buckets']
```




```{python}
# downloads for preprints on osfpreprints
query = {
    "query": {
         "term" : { "provider_id" : "osf" }
    },
     "aggs" : {
        "preprints_from_2019": {
            "filter": {
                "range" : {
                    "timestamp" : {
                        "gte" : "2018-01-01",
                        "lt" : "2019-12-31"
                    }
                }
            },
            "aggs": {
                "users" : {
                    "terms" : {
                        "field" : "preprint_id",
                        "size" : 250
                    }
                }
            }
        }
    }
}


payload = {
    'data': {
        'type': 'preprint_metrics',
        'attributes': {
            'query': query
        }
    }
}

res = requests.post(post_url, headers=headers, json=payload)
osf_downloads = res.json()['aggregations']['preprints_from_2019']['users']['buckets']
```

```{python}
# downloads for preprints on OSF in a specifc timeframe by user by day
query = {
    "query": {
         "term" : { "provider_id" : "osf" }
    },
     "aggs" : {
        "preprints_from_2019": {
            "filter": {
                "range" : {
                    "timestamp" : {
                        "gte" : "2018-01-01",
                        "lt" : "2019-12-31"
                    }
                }
            },
            "aggs": {
                "users" : {
                    "terms" : {
                        "field" : "user_id",
                        "size" : 250
                    },
                    "aggs": {
                      "downloads_per_day" : {
                        "date_histogram" :{
                          "field":"timestamp",
                          "interval":"day",
                          "format": "yyyy-MM-dd HH:mm"
                        }
                      }
                    }
                }
            }
        }
    }
}


payload = {
    'data': {
        'type': 'preprint_metrics',
        'attributes': {
            'query': query
        }
    }
}

res = requests.post(post_url, headers=headers, json=payload)
downloads_byuser_byday = res.json()['aggregations']['preprints_from_2019']['users']['buckets']
```

```{python 3level agg}
# downloads for preprints on OSF in a specifc timeframe by user by day by preprint
query = {
    "query": {
         "term" : { "provider_id" : "osf" }
    },
     "aggs" : {
        "preprints_from_2019": {
            "filter": {
                "range" : {
                    "timestamp" : {
                        "gte" : "2018-01-01",
                        "lt" : "2019-12-31"
                    }
                }
            },
            "aggs": {
                "users" : {
                    "terms" : {
                        "field" : "user_id",
                        "size" : 250
                    },
                    "aggs": {
                      "downloads_per_day" : {
                        "date_histogram" :{
                          "field":"timestamp",
                          "interval":"day",
                          "format": "yyyy-MM-dd HH:mm"
                        },
                        "aggs":{
                          "preprints" : {
                            "terms" :{
                              "field" : "preprint_id"
                            }
                          }
                        }
                      }
                    }
                }
            }
        }
    }
}


payload = {
    'data': {
        'type': 'preprint_metrics',
        'attributes': {
            'query': query
        }
    }
}

res = requests.post(post_url, headers=headers, json=payload)
downloads_byuser_byday_bypreprint = res.json()['aggregations']['preprints_from_2019']['users']['buckets']
```

```{python}
# downloads by user by second for a given time window & preprint

query = {
    "query": {
         "term" : { "preprint_id" : "c8ufs" }
    },
     "aggs" : {
        "preprints_from_2019": {
            "filter": {
                "range" : {
                    "timestamp" : {
                        "gte" : "2018-01-01",
                        "lt" : "2020-03-13"
                    }
                }
            },
            "aggs": {
                "users" : {
                    "terms" : {
                        "field" : "user_id",
                        "size" : 250
                    },
                    "aggs": {
                      "downloads_per_day" : {
                        "date_histogram" :{
                          "field":"timestamp",
                          "interval":"second",
                          "format": "yyyy-MM-dd HH:mm:ss"
                        }
                      }
                    }
                }
            }
        }
    }
}


payload = {
    'data': {
        'type': 'preprint_metrics',
        'attributes': {
            'query': query
        }
    }
}

res = requests.post(post_url, headers=headers, json=payload)
downloads_byuser_byday_forapreprint = res.json()['aggregations']['preprints_from_2019']['users']['buckets']

## same query, just using sloan_id rather than user_id
query = {
    "query": {
         "term" : { "preprint_id" : "c8ufs" }
    },
     "aggs" : {
        "preprints_from_2019": {
            "filter": {
                "range" : {
                    "timestamp" : {
                        "gte" : "2018-01-01",
                        "lt" : "2020-03-13"
                    }
                }
            },
            "aggs": {
                "users" : {
                    "terms" : {
                        "field" : "sloan_id",
                        "size" : 250
                    },
                    "aggs": {
                      "downloads_per_day" : {
                        "date_histogram" :{
                          "field":"timestamp",
                          "interval":"second",
                          "format": "yyyy-MM-dd HH:mm:ss"
                        }
                      }
                    }
                }
            }
        }
    }
}


payload = {
    'data': {
        'type': 'preprint_metrics',
        'attributes': {
            'query': query
        }
    }
}

res = requests.post(post_url, headers=headers, json=payload)
downloads_bysloanid_byday_forapreprint = res.json()['aggregations']['preprints_from_2019']['users']['buckets']
```

```{r}
# turning output of downloads_byuser_byday_forapreprint into a usable dataframe

downloads_byuser_byday_forapreprint_df <- bind_rows(py$downloads_byuser_byday_forapreprint) %>% unnest(downloads_per_day)

downloads_byuser_byday_bypreprint_df %>%
  mutate(date = map_chr(downloads_per_day, 'key_as_string'),
         downloads = map_dbl(downloads_per_day, 'doc_count')) %>%
  rename(user_id = key,
        tot_pp_downloads = doc_count) %>%
  select(-downloads_per_day)
```


