---
title: "preprint_vsds_collection"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# loading required libraries
library(tidyverse)
library(osfr)
library(reticulate)
library(jsonlite)
library(lubridate)

url <- 'https://api.osf.io/_/metrics/preprints/'
osf_auth <- Sys.getenv("osf_preprintimpact_auth")
auth_header <- httr::add_headers('Authorization' = paste('Bearer', osf_auth))

use_condaenv(condaenv = "myenv", conda = "/Users/courtneysoderberg/opt/anaconda3/bin/python")

curr_time <- now('UTC')
yesterday <- as.Date(curr_time) - 1
```

```{r}
# reading in preprint data
new_pp <- read_csv('/Users/courtneysoderberg/Documents/data-science/Sloan_grant/preprint_info.csv') %>% #use absolute path for cron job
              filter(date_published >= yesterday) %>%
              mutate(lt = curr_time,
                     lt_string = gsub(" ", "T", lt),
                     gte = date_published, 
                     gte_string = gsub(" ", "T", gte),
                     run_date = as.Date(curr_time),
                     end_date = ymd_hms(curr_time) + days(14))

coi_pp_dc <- read_csv('/Users/courtneysoderberg/Documents/data-science/Sloan_grant/coi_pp_dc.csv') %>%
                filter(end_date >= curr_time,
                       run_date >= yesterday) %>%
                mutate(gte = lt,
                       lt = curr_time,
                       run_date = as.Date(curr_time)) %>%
                bind_rows(new_pp)
```

```{python}
pp = r.new_pp #get pandas df of R object

import requests
import pandas as pd

METRICS_BASE = r.url
TOKEN = r.osf_auth

headers = {
    'Content-Type': 'application/vnd.api+json',
    'Authorization': 'Bearer {}'.format(TOKEN)
}

post_url = '{}views/'.format(METRICS_BASE)

# set up empty dataframe with the right column names
test_df = pd.DataFrame(columns=['guid', 'user_id', 'date', 'view_count'])

# loop through all the guids that need to be called that day
for i in range(len(pp.guid)):

  # get guid, and start and end days to use in query for each preprint
  lte_date = pp['lt_string'][i]
  gte_date = pp['gte_string'][i]
  guid = pp['guid'][i]
  
  # set up query for getting views per preprint per user_id in timeframe
  query = {
      "query": {
           "term" : { "preprint_id" : guid } # example pp guid
      },
       "aggs" : {
          "download_timeframe": {
              "filter": {
                  "range" : {
                      "timestamp" : {
                          "gte" : gte_date,
                          "lte" : lte_date
                      }
                  }
              },
              "aggs": {
                  "users" : {
                      "terms" : {
                          "field" : "user_id",
                          "size" : 5000
                      },
                      "aggs": {
                        "downloads_per_day" : {
                          "date_histogram" :{
                            "field":"timestamp",
                            "interval":"hour",
                            "format": "yyyy-MM-dd HH:mm:ss"
                          }
                        }
                      }
                  }
              }
          }
      }
  }
  
  
  payload = {
      'data': {
          'type': 'preprint_metrics',
          'attributes': {
              'query': query
          }
      }
  }
  
  # make call using query & payload from above
  res = requests.post(post_url, headers=headers, json=payload)
  pp_views_byuser = res.json()['aggregations']['download_timeframe']['users']['buckets']


  if len(pp_views_byuser) > 0: # only parse query output if there were actually views/downloads to parse
    
    # loop through each person in output
    for x in range(len(pp_views_byuser)):
      
      # for each person, save their dictionary that contatins their actions
      test_keyaccess = pp_views_byuser[x][key]
      
      # loop through each item in their 'buckets' which in this case is each timestamp
      for j in range(len(test_keyaccess['buckets'])):
        
        # append new row with info for the preprint, the user, the timestamp, and the action count
        test_df = test_df.append({'guid': guid, 'user_id': pp_views_byuser[x]['key'], 'date': test_keyaccess['buckets'][j]['key_as_string'], 'view_count': test_keyaccess['buckets'][j]['doc_count']}, ignore_index= True)
  else:
    print('length 0')
```

```{python}
query = {
    "query": {
         "term" : { "preprint_id" : "9yqs8" } # example pp guid
    },
     "aggs" : {
        "download_timeframe": {
            "filter": {
                "range" : {
                    "timestamp" : {
                        "gte" : "2020-03-01",
                        "lte" : "2020-03-02"
                    }
                }
            },
            "aggs": {
                "users" : {
                    "terms" : {
                        "field" : "user_id",
                        "size" : 5000
                    },
                    "aggs": {
                      "downloads_per_day" : {
                        "date_histogram" :{
                          "field":"timestamp",
                          "interval":"hour",
                          "format": "yyyy-MM-dd HH:mm:ss"
                        }
                      }
                    }
                }
            }
        }
    }
}


payload = {
    'data': {
        'type': 'preprint_metrics',
        'attributes': {
            'query': query
        }
    }
}

res = requests.post(post_url, headers=headers, json=payload)
pp_views_byuser203 = res.json()['aggregations']['download_timeframe']['users']['buckets']
```



```{python}

####this actually words for a given guid
test_df = pd.DataFrame(columns=['guid', 'user_id', 'date', 'view_count'])

for x in range(len(short_version)):
  test_keyaccess = short_version[x][key]
  for j in range(len(test_keyaccess['buckets'])):
    test_df = test_df.append({'guid': 'something', 'user_id': short_version[x]['key'], 'date': test_keyaccess['buckets'][j]['key_as_string'], 'view_count': test_keyaccess['buckets'][j]['doc_count']}, ignore_index= True)

print(test_df)
```



```{r}
names(py$test_list) <- c('test1', 'test2', 'test3')
```

