---
title: "User Generation By Product"
output: 
  flexdashboard::flex_dashboard:
    orientation: column
    theme: bootstrap
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(gt)
library(here)
library(highcharter)
library(dichromat)

user_generation_data <- read_csv(here::here('Quarterly_Reports/data_for_mockup.csv'))

cols <- c('#34495D', '#3277A2', '#14A4EB', '#A8C8DD')
```

Column {data-width=200}
-----------------------------------------------------------------------

### Variable Definitions

* *variable1*: Here is a definition

* *variable2*: Here is another defintion to remind everyone exactly what these different things are picking up since they may be easily forgottn

* Here are some general notes if needed

Column {data-width=500}
-----------------------------------------------------------------------

### Last Quarter's New Users {data-height=500}

Some description of the table below. 


```{r}
user_generation_data %>%
  group_by(product, user_type) %>%
  slice(1L) %>%
  ungroup() %>%
  select(-date) %>%
  pivot_wider(names_from = user_type, values_from = new_n) %>%
  gt() %>%
  cols_label(
    product = 'Product',
    new_active = 'Newly Registered',
    nonreg_added = 'Newly Invited',
    nonreg_claimed = 'Newly Claimed'
  ) %>%
  cols_align(align = 'center') %>%
  cols_width(everything() ~ px(105))
  
  
```

### Unregistered contributors added by products {data-height=500}

```{r}
user_generation_data %>%
  filter(user_type == 'nonreg_added') %>%
  hchart(., type = 'line',
         hcaes(x = date,
               y = new_n,
               group = product)) %>%
  hc_tooltip(table = TRUE, sort = TRUE) %>%
  hc_plotOptions(series = list(marker = list(enabled = FALSE))) %>%
  hc_xAxis(title = list(text = ""), tickInterval = 86400000 * 30) %>% #tick interval for date in milliseconds
  hc_yAxis(title = list(text = "Newly Registered Users")) %>%
  hc_colors(cols) %>%
  hc_exporting(
    enabled = TRUE, filename="newuser_generation", 
              formAttributes=list(target="_blank"),
               buttons=list(contextButton=list(
               text="Export", theme=list(fill="transparent"))))
```




Column {data-width=500}
-----------------------------------------------------------------------
### New users generated by product {data-height=500}

```{r}
user_generation_data %>%
  filter(user_type == 'new_active') %>%
  hchart(., type = 'line',
         hcaes(x = date,
               y = new_n,
               group = product)) %>%
  hc_tooltip(table = TRUE, sort = TRUE) %>%
  hc_plotOptions(series = list(marker = list(enabled = FALSE))) %>%
  hc_xAxis(title = list(text = ""), tickInterval = 86400000 * 30) %>% #tick interval for date in milliseconds
  hc_yAxis(title = list(text = "Newly Registered Users")) %>%
  hc_colors(cols) %>%
  hc_exporting(
    enabled = TRUE, filename="newuser_generation", 
              formAttributes=list(target="_blank"),
               buttons=list(contextButton=list(
               text="Export", theme=list(fill="transparent"))))
```

### Unregistered contributors claiming accounts by product {data-height=500}

```{r}
user_generation_data %>%
  filter(user_type == 'nonreg_claimed') %>%
  hchart(., type = 'line',
         hcaes(x = date,
               y = new_n,
               group = product)) %>%
  hc_tooltip(table = TRUE, sort = TRUE) %>%
  hc_plotOptions(series = list(marker = list(enabled = FALSE))) %>%
  hc_xAxis(title = list(text = ""), tickInterval = 86400000 * 30) %>% #tick interval for date in milliseconds
  hc_yAxis(title = list(text = "Newly Registered Users")) %>%
  hc_colors(cols) %>%
  hc_exporting(
    enabled = TRUE, filename="newuser_generation", 
              formAttributes=list(target="_blank"),
               buttons=list(contextButton=list(
               text="Export", theme=list(fill="transparent"))))
```






