---
title: "Downloads by Product"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: bootstrap
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(highcharter)
library(lubridate)
library(osfr)

#download & read-in data
osf_retrieve_file('https://osf.io/wd7gs/') %>%
  osf_download(path = here::here('product_downloads/'), conflicts = "overwrite")

last_quarter_data <- read_csv(here::here('/product_downloads/last_Q_downloads.csv'))

download_data <- read_csv(here::here('product_downloads/monthly_downloads_by_product.csv')) %>%
                    rbind(last_quarter_data) %>%
                    mutate(total = osf4m_downloads + quickfile_downloads + reg_downloads + pp_downloads + osfnode_download,
                           date = as.Date(date)) %>%
                    arrange(date) %>%
                    rename(Quickfiles = quickfile_downloads,
                           Registrations = reg_downloads,
                           Preprints = pp_downloads,
                           `OSF Nodes` = osfnode_download,
                           Collections = collection_downloads,
                           Institutions = inst_downloads,
                           OSF4M = osf4m_downloads,
                           `Supp Nodes` = suppnode_downloads,
                           `OSF General` = osfgen_download)

# reupload OSF data
write_csv(download_data, 'monthly_downloads_by_product.csv')

osf_retrieve_node('https://osf.io/5hw9s/') %>%
  osf_ls_files() %>%
  filter(name == 'Downloads by Product') %>%
  osf_upload('monthly_downloads_by_product.csv', conflicts = 'overwrite')
```

Inputs {.sidebar}
-------------------------------------

* **OSF Nodes** counts any osf node, regardless of its 'type' (e.g. osf4m, collection, suppnode)
* **Preprints** are download of preprint files, startign the day they became preprints
* **Registrations** are downloads of files on registrations
* **Collections** count downloads on files anywhere in a project connected to a collection, starting from when the project was submitted to the collection
* **Instituions** count downloads for files connected to affiliated nodes
* **OSF4M** count downloads of osf4m nodes
* **Supp Nodes** count downloads of files on preprint suppnodes, starting the day the node was connected as a suppnode
* **OSF General** count downloads of files on non-registration osf nodes that are not: in a collection, a suppnode, an osf4m, or affiliated


Row 
-------------------------------------

### Total monthly downloads

```{r}
download_data  %>%
  filter(date >= '2016-08-01') %>%
  hchart(., type = 'line',
         hcaes(x = date,
               y = total)) %>%
  hc_tooltip(table = TRUE, sort = TRUE) %>%
  hc_plotOptions(series = list(marker = list(enabled = FALSE))) %>%
  hc_xAxis(title = list(text = ""), tickInterval = 86400000 * 30) %>% #tick interval for date in milliseconds
  hc_yAxis(title = list(text = "Downloads")) %>%
  hc_exporting(
    enabled = TRUE, filename="total_downloads", 
              formAttributes=list(target="_blank"),
               buttons=list(contextButton=list(
               text="Export", theme=list(fill="transparent"))))
```

Row {.tabset .tabset-fade}
-------------------------------------

### Raw Downloads by Product

```{r}
download_data  %>%
  filter(date >= '2016-08-01') %>%
  select(date, Quickfiles, Registrations, Preprints, `OSF Nodes`) %>%
  pivot_longer(cols = Quickfiles:`OSF Nodes`, names_to = 'product', values_to = 'downloads') %>%
  hchart(., type = 'line',
         hcaes(x = date,
               y = downloads,
               group = product)) %>%
  hc_tooltip(table = TRUE, sort = TRUE) %>%
  hc_plotOptions(series = list(marker = list(enabled = FALSE))) %>%
  hc_xAxis(title = list(text = ""), tickInterval = 86400000 * 30) %>% #tick interval for date in milliseconds
  hc_yAxis(title = list(text = "Downloads")) %>%
  hc_exporting(
    enabled = TRUE, filename="product_downloads", 
              formAttributes=list(target="_blank"),
               buttons=list(contextButton=list(
               text="Export", theme=list(fill="transparent"))))
```

### Percentage Downloads by Product

```{r}
download_data  %>%
  filter(date >= '2016-08-01') %>%
  select(date, Quickfiles, Registrations, Preprints, `OSF Nodes`) %>%
  pivot_longer(cols = Quickfiles:`OSF Nodes`, names_to = 'product', values_to = 'downloads') %>%
  group_by(date) %>%
  mutate(perc = round((100 * downloads)/sum(downloads),2)) %>%
  hchart(., type = 'line',
         hcaes(x = date,
               y = perc,
               group = product)) %>%
  hc_tooltip(table = TRUE, sort = TRUE) %>%
  hc_plotOptions(series = list(marker = list(enabled = FALSE))) %>%
  hc_xAxis(title = list(text = ""), tickInterval = 86400000 * 30) %>% #tick interval for date in milliseconds
  hc_yAxis(title = list(text = "Percent Downloads")) %>%
  hc_exporting(
    enabled = TRUE, filename="product_perc_downloads", 
              formAttributes=list(target="_blank"),
               buttons=list(contextButton=list(
               text="Export", theme=list(fill="transparent"))))
```

Row {.tabset .tabset-fade}
-------------------------------------

### Raw Downloads by OSF type

```{r}
download_data  %>%
  filter(date >= '2016-08-01') %>%
  select(date, OSF4M, `Supp Nodes`, Institutions, Collections, `OSF General`) %>%
  pivot_longer(cols = OSF4M:`OSF General`, names_to = 'product', values_to = 'downloads') %>%
  hchart(., type = 'line',
         hcaes(x = date,
               y = downloads,
               group = product)) %>%
  hc_tooltip(table = TRUE, sort = TRUE) %>%
  hc_plotOptions(series = list(marker = list(enabled = FALSE))) %>%
  hc_xAxis(title = list(text = ""), tickInterval = 86400000 * 30) %>% #tick interval for date in milliseconds
  hc_yAxis(title = list(text = "Downloads")) %>%
  hc_exporting(
    enabled = TRUE, filename="osf_product_downloads", 
              formAttributes=list(target="_blank"),
               buttons=list(contextButton=list(
               text="Export", theme=list(fill="transparent"))))
```


### Percentage Downloads by OSF type

```{r}
download_data  %>%
  filter(date >= '2016-08-01') %>%
  mutate(denominator = `OSF Nodes`) %>%
  select(date, OSF4M, `Supp Nodes`, Institutions, Collections, `OSF General`, denominator) %>%
  pivot_longer(cols = OSF4M:`OSF General`, names_to = 'product', values_to = 'downloads') %>%
  mutate(perc = round(100 * downloads/denominator),2) %>%
  hchart(., type = 'line',
         hcaes(x = date,
               y = perc,
               group = product)) %>%
  hc_tooltip(table = TRUE, sort = TRUE) %>%
  hc_plotOptions(series = list(marker = list(enabled = FALSE))) %>%
  hc_xAxis(title = list(text = ""), tickInterval = 86400000 * 30) %>% #tick interval for date in milliseconds
  hc_yAxis(title = list(text = "Downloads")) %>%
  hc_exporting(
    enabled = TRUE, filename="osf_product_downloads", 
              formAttributes=list(target="_blank"),
               buttons=list(contextButton=list(
               text="Export", theme=list(fill="transparent"))))
```

